version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: chatapp-postgres
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: chatapp
      POSTGRES_PASSWORD: chatapp_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatapp -d chat_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chatapp-network

volumes:
  postgres_data:
    driver: local

networks:
  chatapp-network:
    driver: bridge
